// Generated by @decocms/blocks-migrate from a v7 site. It's your code now: edit it freely.
// Each block has a short name plus an alias under every v7 name saved content stores
// (see /next/renames-and-migrations).
import type { Blocks, Route, Seo } from "@decocms/blocks";
import shopifyProductDetailsPage from "../src/vendor/shopify/loaders/ProductDetailsPage";
import shopifyProductList from "../src/vendor/shopify/loaders/ProductList";
import shopifyProductListingPage from "../src/vendor/shopify/loaders/ProductListingPage";
import websiteGoogleFonts from "../src/vendor/website/loaders/fonts/googleFonts";

/** What a section block returns: the component to render and its props (/next/rendering). */
export interface BlockDescriptor {
  component: string;
  props: unknown;
}

/** A page with its blocks resolved. */
export interface ResolvedPage extends Route {
  seo?: Seo;
  sections: BlockDescriptor[];
}

/** A v7 section's saved props: its loader's input when it has one, else its component's props. */
type PropsOf<M> = M extends { loader: (props: infer P, ...rest: any[]) => unknown }
  ? P
  : M extends { default: (props: infer P, ...rest: any[]) => unknown }
    ? P
    : Record<string, never>;

const section =
  <M>(component: string) =>
  (props: PropsOf<M>): BlockDescriptor => ({ component, props });

const animation = section<typeof import("../src/sections/Animation/Animation")>("animation");
const categoryBanner = section<typeof import("../src/sections/Category/CategoryBanner")>("category-banner");
const categoryGrid = section<typeof import("../src/sections/Category/CategoryGrid")>("category-grid");
const faq = section<typeof import("../src/sections/Content/Faq")>("faq");
const hero = section<typeof import("../src/sections/Content/Hero")>("hero");
const intro = section<typeof import("../src/sections/Content/Intro")>("intro");
const logos = section<typeof import("../src/sections/Content/Logos")>("logos");
const footer = section<typeof import("../src/sections/Footer/Footer")>("footer");
const header = section<typeof import("../src/sections/Header/Header")>("header");
const banner = section<typeof import("../src/sections/Images/Banner")>("banner");
const carousel = section<typeof import("../src/sections/Images/Carousel")>("carousel");
const imageGallery = section<typeof import("../src/sections/Images/ImageGallery")>("image-gallery");
const shoppableBanner = section<typeof import("../src/sections/Images/ShoppableBanner")>("shoppable-banner");
const linkTree = section<typeof import("../src/sections/Links/LinkTree")>("link-tree");
const campaignTimer = section<typeof import("../src/sections/Miscellaneous/CampaignTimer")>("campaign-timer");
const cookieConsent = section<typeof import("../src/sections/Miscellaneous/CookieConsent")>("cookie-consent");
const newsletter = section<typeof import("../src/sections/Newsletter/Newsletter")>("newsletter");
const productDetails = section<typeof import("../src/sections/Product/ProductDetails")>("product-details");
const productShelf = section<typeof import("../src/sections/Product/ProductShelf")>("product-shelf");
const productShelfTabbed = section<typeof import("../src/sections/Product/ProductShelfTabbed")>("product-shelf-tabbed");
const searchResult = section<typeof import("../src/sections/Product/SearchResult")>("search-result");
const shelfWithImage = section<typeof import("../src/sections/Product/ShelfWithImage")>("shelf-with-image");
const wishlist = section<typeof import("../src/sections/Product/Wishlist")>("wishlist");
const instagramPosts = section<typeof import("../src/sections/Social/InstagramPosts")>("instagram-posts");
const whatsApp = section<typeof import("../src/sections/Social/WhatsApp")>("whats-app");
const theme = section<typeof import("../src/sections/Theme/Theme")>("theme");

export default {
  page: (input: ResolvedPage) => input,
  "shopify-product-details-page": shopifyProductDetailsPage,
  "shopify/loaders/ProductDetailsPage.ts": shopifyProductDetailsPage,
  "shopify-product-list": shopifyProductList,
  "shopify/loaders/ProductList.ts": shopifyProductList,
  "shopify-product-listing-page": shopifyProductListingPage,
  "shopify/loaders/ProductListingPage.ts": shopifyProductListingPage,
  "animation": animation,
  "site/sections/Animation/Animation.tsx": animation,
  "category-banner": categoryBanner,
  "site/sections/Category/CategoryBanner.tsx": categoryBanner,
  "category-grid": categoryGrid,
  "site/sections/Category/CategoryGrid.tsx": categoryGrid,
  "faq": faq,
  "site/sections/Content/Faq.tsx": faq,
  "hero": hero,
  "site/sections/Content/Hero.tsx": hero,
  "intro": intro,
  "site/sections/Content/Intro.tsx": intro,
  "logos": logos,
  "site/sections/Content/Logos.tsx": logos,
  "footer": footer,
  "site/sections/Footer/Footer.tsx": footer,
  "header": header,
  "site/sections/Header/Header.tsx": header,
  "banner": banner,
  "site/sections/Images/Banner.tsx": banner,
  "carousel": carousel,
  "site/sections/Images/Carousel.tsx": carousel,
  "image-gallery": imageGallery,
  "site/sections/Images/ImageGallery.tsx": imageGallery,
  "shoppable-banner": shoppableBanner,
  "site/sections/Images/ShoppableBanner.tsx": shoppableBanner,
  "link-tree": linkTree,
  "site/sections/Links/LinkTree.tsx": linkTree,
  "campaign-timer": campaignTimer,
  "site/sections/Miscellaneous/CampaignTimer.tsx": campaignTimer,
  "cookie-consent": cookieConsent,
  "site/sections/Miscellaneous/CookieConsent.tsx": cookieConsent,
  "newsletter": newsletter,
  "site/sections/Newsletter/Newsletter.tsx": newsletter,
  "product-details": productDetails,
  "site/sections/Product/ProductDetails.tsx": productDetails,
  "product-shelf": productShelf,
  "site/sections/Product/ProductShelf.tsx": productShelf,
  "product-shelf-tabbed": productShelfTabbed,
  "site/sections/Product/ProductShelfTabbed.tsx": productShelfTabbed,
  "search-result": searchResult,
  "site/sections/Product/SearchResult.tsx": searchResult,
  "shelf-with-image": shelfWithImage,
  "site/sections/Product/ShelfWithImage.tsx": shelfWithImage,
  "wishlist": wishlist,
  "site/sections/Product/Wishlist.tsx": wishlist,
  "instagram-posts": instagramPosts,
  "site/sections/Social/InstagramPosts.tsx": instagramPosts,
  "whats-app": whatsApp,
  "site/sections/Social/WhatsApp.tsx": whatsApp,
  "theme": theme,
  "site/sections/Theme/Theme.tsx": theme,
  "website-google-fonts": websiteGoogleFonts,
  "website/loaders/fonts/googleFonts.ts": websiteGoogleFonts,
} satisfies Blocks;
