// Auto-generated by @decocms/blocks-cli/scripts/generate-loaders.ts
// Do not edit manually. Run `npm run generate:loaders` to update.
//
// Pass-through loader/action entries for COMMERCE_LOADERS.
// Custom-wired entries should be excluded via --exclude and added manually in setup.ts.

export const siteLoaders: Record<string, (props: any, request?: Request) => Promise<any>> = {
  "site/actions/address/submit": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/address/submit");
    return (mod.default as any)(props, request);
  },
  "site/actions/address/submit.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/address/submit");
    return (mod.default as any)(props, request);
  },
  "site/actions/newsletter/subscribe": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/newsletter/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/newsletter/subscribe.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/newsletter/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/notifyMe/subscribe": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/notifyMe/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/notifyMe/subscribe.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/notifyMe/subscribe");
    return (mod.default as any)(props, request);
  },
  "site/actions/shipping/simulate": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/shipping/simulate");
    return (mod.default as any)(props, request);
  },
  "site/actions/shipping/simulate.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/shipping/simulate");
    return (mod.default as any)(props, request);
  },
  "site/actions/wishlist/submit": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/wishlist/submit");
    return (mod.default as any)(props, request);
  },
  "site/actions/wishlist/submit.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/actions/wishlist/submit");
    return (mod.default as any)(props, request);
  },
  "site/loaders/address": async (props: any, request?: Request) => {
    const mod = await import("../src/loaders/address");
    return (mod.default as any)(props, request);
  },
  "site/loaders/address.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/loaders/address");
    return (mod.default as any)(props, request);
  },
  "site/loaders/user": async (props: any, request?: Request) => {
    const mod = await import("../src/loaders/user");
    return (mod.default as any)(props, request);
  },
  "site/loaders/user.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/loaders/user");
    return (mod.default as any)(props, request);
  },
  "site/loaders/wishlist": async (props: any, request?: Request) => {
    const mod = await import("../src/loaders/wishlist");
    return (mod.default as any)(props, request);
  },
  "site/loaders/wishlist.ts": async (props: any, request?: Request) => {
    const mod = await import("../src/loaders/wishlist");
    return (mod.default as any)(props, request);
  },
};
