// Auto-generated by @decocms/start/scripts/generate-loaders.ts
// Do not edit manually. Run `npm run generate:loaders` to update.
//
// Pass-through loader/action entries for COMMERCE_LOADERS.
// Custom-wired entries should be excluded via --exclude and added manually in setup.ts.

export const siteLoaders: Record<string, (props: any) => Promise<any>> = {
  "site/actions/wishlist/submit": async (props: any) => {
    const mod = await import("../../actions/wishlist/submit");
    return mod.default(props);
  },
  "site/actions/wishlist/submit.ts": async (props: any) => {
    const mod = await import("../../actions/wishlist/submit");
    return mod.default(props);
  },
  "site/loaders/user": async (props: any) => {
    const mod = await import("../../loaders/user");
    return mod.default(props);
  },
  "site/loaders/user.ts": async (props: any) => {
    const mod = await import("../../loaders/user");
    return mod.default(props);
  },
  "site/loaders/wishlist": async (props: any) => {
    const mod = await import("../../loaders/wishlist");
    return mod.default(props);
  },
  "site/loaders/wishlist.ts": async (props: any) => {
    const mod = await import("../../loaders/wishlist");
    return mod.default(props);
  },
};
