// Auto-generated by @decocms/start/scripts/generate-sections.ts
// Do not edit manually. Add convention exports to your section files instead.
//
// Supported conventions:
//   export const eager = true       → always SSR'd (never deferred)
//   export const cache = "listing"  → SWR-cached section loader results
//   export const layout = true      → cached as layout (Header, Footer, Theme)
//   export const sync = true        → bundled synchronously (not lazy-loaded)
//   export const clientOnly = true  → skip SSR (client-only rendering)
//   export const seo = true         → SEO section (provides page head data)
//   export function LoadingFallback → skeleton shown while section loads

import * as _sync0 from "../../sections/Footer/Footer";
import * as _sync1 from "../../sections/Header/Header";
import * as _sync2 from "../../sections/Theme/Theme";
import { LoadingFallback as _fb0 } from "../../sections/Category/CategoryGrid";
import { LoadingFallback as _fb1 } from "../../sections/Images/Banner";
import { LoadingFallback as _fb2 } from "../../sections/Images/Carousel";
import { LoadingFallback as _fb3 } from "../../sections/Images/ImageGallery";
import { LoadingFallback as _fb4 } from "../../sections/Images/ShoppableBanner";
import { LoadingFallback as _fb5 } from "../../sections/Links/LinkTree";
import { LoadingFallback as _fb6 } from "../../sections/Miscellaneous/CampaignTimer";
import { LoadingFallback as _fb7 } from "../../sections/Miscellaneous/CookieConsent";
import { LoadingFallback as _fb8 } from "../../sections/Newsletter/Newsletter";
import { LoadingFallback as _fb9 } from "../../sections/Product/ProductDetails";
import { LoadingFallback as _fb10 } from "../../sections/Product/ProductShelf";
import { LoadingFallback as _fb11 } from "../../sections/Product/ProductShelfTabbed";
import { LoadingFallback as _fb12 } from "../../sections/Product/SearchResult";
import { LoadingFallback as _fb13 } from "../../sections/Product/ShelfWithImage";
import { LoadingFallback as _fb14 } from "../../sections/Product/Wishlist";
import { LoadingFallback as _fb15 } from "../../sections/Social/InstagramPosts";
import { LoadingFallback as _fb16 } from "../../sections/Social/WhatsApp";

export interface SectionMetaEntry {
  eager?: boolean;
  cache?: string;
  layout?: boolean;
  sync?: boolean;
  clientOnly?: boolean;
  seo?: boolean;
  hasLoadingFallback?: boolean;
}

export const sectionMeta: Record<string, SectionMetaEntry> = {
  "site/sections/Category/CategoryGrid.tsx": { hasLoadingFallback: true },
  "site/sections/Footer/Footer.tsx": { eager: true, sync: true, layout: true, hasLoadingFallback: true },
  "site/sections/Header/Header.tsx": { eager: true, sync: true, layout: true, hasLoadingFallback: true },
  "site/sections/Images/Banner.tsx": { hasLoadingFallback: true },
  "site/sections/Images/Carousel.tsx": { cache: "listing", hasLoadingFallback: true },
  "site/sections/Images/ImageGallery.tsx": { hasLoadingFallback: true },
  "site/sections/Images/ShoppableBanner.tsx": { hasLoadingFallback: true },
  "site/sections/Links/LinkTree.tsx": { hasLoadingFallback: true },
  "site/sections/Miscellaneous/CampaignTimer.tsx": { hasLoadingFallback: true },
  "site/sections/Miscellaneous/CookieConsent.tsx": { hasLoadingFallback: true },
  "site/sections/Newsletter/Newsletter.tsx": { hasLoadingFallback: true },
  "site/sections/Product/ProductDetails.tsx": { hasLoadingFallback: true },
  "site/sections/Product/ProductShelf.tsx": { hasLoadingFallback: true },
  "site/sections/Product/ProductShelfTabbed.tsx": { hasLoadingFallback: true },
  "site/sections/Product/SearchResult.tsx": { cache: "listing", hasLoadingFallback: true },
  "site/sections/Product/ShelfWithImage.tsx": { hasLoadingFallback: true },
  "site/sections/Product/Wishlist.tsx": { hasLoadingFallback: true },
  "site/sections/Social/InstagramPosts.tsx": { hasLoadingFallback: true },
  "site/sections/Social/WhatsApp.tsx": { hasLoadingFallback: true },
  "site/sections/Theme/Theme.tsx": { eager: true, sync: true, layout: true, hasLoadingFallback: true },
};

export const syncComponents: Record<string, any> = {
  "site/sections/Footer/Footer.tsx": _sync0,
  "site/sections/Header/Header.tsx": _sync1,
  "site/sections/Theme/Theme.tsx": _sync2,
};

export const loadingFallbacks: Record<string, React.ComponentType<any>> = {
  "site/sections/Category/CategoryGrid.tsx": _fb0,
  "site/sections/Footer/Footer.tsx": _sync0.LoadingFallback,
  "site/sections/Header/Header.tsx": _sync1.LoadingFallback,
  "site/sections/Images/Banner.tsx": _fb1,
  "site/sections/Images/Carousel.tsx": _fb2,
  "site/sections/Images/ImageGallery.tsx": _fb3,
  "site/sections/Images/ShoppableBanner.tsx": _fb4,
  "site/sections/Links/LinkTree.tsx": _fb5,
  "site/sections/Miscellaneous/CampaignTimer.tsx": _fb6,
  "site/sections/Miscellaneous/CookieConsent.tsx": _fb7,
  "site/sections/Newsletter/Newsletter.tsx": _fb8,
  "site/sections/Product/ProductDetails.tsx": _fb9,
  "site/sections/Product/ProductShelf.tsx": _fb10,
  "site/sections/Product/ProductShelfTabbed.tsx": _fb11,
  "site/sections/Product/SearchResult.tsx": _fb12,
  "site/sections/Product/ShelfWithImage.tsx": _fb13,
  "site/sections/Product/Wishlist.tsx": _fb14,
  "site/sections/Social/InstagramPosts.tsx": _fb15,
  "site/sections/Social/WhatsApp.tsx": _fb16,
  "site/sections/Theme/Theme.tsx": _sync2.LoadingFallback,
};
